import Head from 'next/head'
import Activity from '../components/Activity'
import Footer from '../components/Footer'
import Message from '../components/Message'

export default function Home() {
  return (
    <div className="w-full px-3 md:px-36">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Message />
      <Activity />
      <Footer />
    </div>
  )
}
